apiVersion: apps/v1
kind: Deployment
metadata:
  name: recaudaciones-demo
  namespace: recaudaciones
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recaudaciones-demo
  strategy:
    type: RollingUpdate
    RollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: recaudaciones-demo
    spec:
      containers:
        - name: recaudaciones-demo
          image: gio0603/reca-web:5fe3199
          env:
            - name: API_BASE
              value: "http://localhost:3001"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
