name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short SHA
        id: vars
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/reca-web
          docker build -t $IMAGE:latest -t $IMAGE:${{ env.SHORT_SHA }} .
          docker push $IMAGE:latest
          docker push $IMAGE:${{ env.SHORT_SHA }}

      - name: Update deployment with new image tag
        run: |
          sed -i "s|\(image: ${{ secrets.DOCKERHUB_USERNAME }}/reca-web:\).*|\1${{ env.SHORT_SHA }}|" k8s/deployment.yaml

      - name: Commit and push updated deployment file
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/gventuraagramonte/demo-recaudaciones.git
          git add k8s/deployment.yaml
          git commit -m "chore: update deployment image tag to ${{ env.SHORT_SHA }}"
          git push
